### ISSUE TITLE
scheduler.RunUntilShutdown causes a deadlock

### ISSUE THREAD

**Issue by AnanthaKrishnaV** [kagkarlsson/db-scheduler#327]
We use db-scheduler to schedule one-time tasks. We have around 10 containers of our app running with each having 8 threads. We see below exception on all containers.  Due to our workflow we have more rows on scheduled_tasks table (~20K). Below exception is form same container(ais-ecr-now-ecr-prod-v00170-6dc89d6fdc-vrx2r) but two different threads(db-scheduler-execute-due-pool-5-thread-1 and db-scheduler-pool-4-thread-6.). Even other thread throws exception here I pasted only two. Any suggestion to mitigate this issue would be helpfull.

 exception: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 153) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   logger: com.github.kagkarlsson.scheduler.Scheduler
   message: Failed while completing execution Execution: task=EICRTask, id=CLOSE_OUT_EICR_1979472_6d16d532-3e49-457f-b344-18b60ddff92a, executionTime=2022-09-25T08:52:49.517Z, picked=true, pickedBy=ais-ecr-now-ecr-prod-v00170-6dc89d6fdc-vrx2r, lastHeartbeat=2022-09-25T22:00:43.546Z, version=2. Execution will likely remain scheduled and locked/picked. The execution should be detected as dead in PT4M, and handled according to the tasks DeadExecutionHandler.com.github.kagkarlsson.jdbc.SQLRuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 153) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.github.kagkarlsson.jdbc.JdbcRunner.translateException(JdbcRunner.java:126)
	at com.github.kagkarlsson.jdbc.JdbcRunner.lambda$execute$2(JdbcRunner.java:93)
	at com.github.kagkarlsson.jdbc.JdbcRunner.withConnection(JdbcRunner.java:140)
	at com.github.kagkarlsson.jdbc.JdbcRunner.execute(JdbcRunner.java:66)
	at com.github.kagkarlsson.jdbc.JdbcRunner.execute(JdbcRunner.java:54)
	at com.github.kagkarlsson.scheduler.JdbcTaskRepository.remove(JdbcTaskRepository.java:155)
	at com.github.kagkarlsson.scheduler.task.ExecutionOperations.stop(ExecutionOperations.java:33)
	at com.github.kagkarlsson.scheduler.task.CompletionHandler$OnCompleteRemove.complete(CompletionHandler.java:33)
	at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.complete(Scheduler.java:373)
	at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.executePickedExecution(Scheduler.java:355)
	at com.github.kagkarlsson.scheduler.Scheduler$PickAndExecute.runButLogExceptions(Scheduler.java:328)
	at com.github.kagkarlsson.scheduler.concurrent.LoggingRunnable.run(LoggingRunnable.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 153) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
	at com.github.kagkarlsson.jdbc.JdbcRunner.lambda$execute$2(JdbcRunner.java:85)
	... 13 common frames omitted

   severity: ERROR
   thread: db-scheduler-pool-4-thread-6
   time: 1664143263.309
   
exception: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 102) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   logger: com.github.kagkarlsson.scheduler.RunUntilShutdown
   message: Unhandled exception. Will keep running.com.github.kagkarlsson.jdbc.SQLRuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 102) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.github.kagkarlsson.jdbc.JdbcRunner.withResultSet(JdbcRunner.java:177)
	at com.github.kagkarlsson.jdbc.JdbcRunner.mapResultSet(JdbcRunner.java:159)
	at com.github.kagkarlsson.jdbc.JdbcRunner.lambda$query$1(JdbcRunner.java:62)
	at com.github.kagkarlsson.jdbc.JdbcRunner.lambda$execute$2(JdbcRunner.java:86)
	at com.github.kagkarlsson.jdbc.JdbcRunner.withConnection(JdbcRunner.java:140)
	at com.github.kagkarlsson.jdbc.JdbcRunner.execute(JdbcRunner.java:66)
	at com.github.kagkarlsson.jdbc.JdbcRunner.query(JdbcRunner.java:62)
	at com.github.kagkarlsson.scheduler.JdbcTaskRepository.getDue(JdbcTaskRepository.java:139)
	at com.github.kagkarlsson.scheduler.Scheduler.executeDue(Scheduler.java:214)
	at com.github.kagkarlsson.scheduler.RunUntilShutdown.run(RunUntilShutdown.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 102) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5448)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1771)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1029)
	at com.github.kagkarlsson.scheduler.JdbcTaskRepository$ExecutionResultSetConsumer.map(JdbcTaskRepository.java:380)
	at com.github.kagkarlsson.scheduler.JdbcTaskRepository$ExecutionResultSetMapper.map(JdbcTaskRepository.java:363)
	at com.github.kagkarlsson.scheduler.JdbcTaskRepository$ExecutionResultSetMapper.map(JdbcTaskRepository.java:350)
	at com.github.kagkarlsson.jdbc.JdbcRunner.lambda$mapResultSet$4(JdbcRunner.java:161)
	at com.github.kagkarlsson.jdbc.JdbcRunner.withResultSet(JdbcRunner.java:175)
	... 14 common frames omitted

   severity: ERROR
   thread: db-scheduler-execute-due-pool-5-thread-1
   time: 1664098959.191
}

**Comment by kagkarlsson** [comment]
Not really sure what this is..

**Comment by kagkarlsson** [comment]
Cannot currently see what would cause a deadlock..

**Comment by kagkarlsson** [comment]
What transaction isolation level are you using?

**Comment by zeevalor** [comment]
READ COMMITTED is the default isolation level for SQL Server. It prevents dirty reads by specifying that statements cannot read data values that have been modified but not yet committed by other transactions. We are running READ COMMITTED

**Comment by kagkarlsson** [comment]
Similar to #348

**Comment by kagkarlsson** [comment]
Closing due to inactivity. Might be fixed.
