### ISSUE TITLE
 Failed to serialize object.  PlainScheduleAndData

### ISSUE THREAD

**Issue by mumubin** [kagkarlsson/db-scheduler#334]
my test code
```
    @SneakyThrows
    @Test
    void dbSchedulerDeleteRecordingJob() {

        final RecurringTaskWithPersistentSchedule<PlainScheduleAndData> task =
                Tasks.recurringWithPersistentSchedule("dynamic-recurring-task", PlainScheduleAndData.class)
                        .execute((taskInstance, executionContext) -> {
                            System.out.println("Instance: '" + taskInstance.getId() + "' ran using persistent schedule: " + taskInstance.getData()
                                    .getSchedule());
                        });


        final Scheduler scheduler = Scheduler
                .create(dataSource, task)
                .serializer(new JacksonSerializer())
                .pollingInterval(Duration.ofSeconds(1))
                .registerShutdownHook()
                .build();


        scheduler.start();

        scheduler.schedule(task.schedulableInstance("id1", new PlainScheduleAndData(Schedules.fixedDelay(Duration.ofMinutes(1)))));
        scheduler.schedule(task.schedulableInstance("id2", new PlainScheduleAndData(Schedules.fixedDelay(Duration.ofSeconds(6)))));
        System.out.println("waiting =============================");
        while (true) {
            sleep(2000L);
        }
```

stacktrace
```
Failed to serialize object.
com.github.kagkarlsson.scheduler.exceptions.SerializationException: Failed to serialize object.
	at com.github.kagkarlsson.scheduler.serializer.JacksonSerializer.serialize(JacksonSerializer.java:71)
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository.lambda$createIfNotExists$0(JdbcTaskRepository.java:106)
	at com.github.kagkarlsson.jdbc.JdbcRunner.lambda$execute$2(JdbcRunner.java:79)
	at com.github.kagkarlsson.jdbc.JdbcRunner.withConnection(JdbcRunner.java:140)
	at com.github.kagkarlsson.jdbc.JdbcRunner.execute(JdbcRunner.java:66)
	at com.github.kagkarlsson.jdbc.JdbcRunner.execute(JdbcRunner.java:54)
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository.createIfNotExists(JdbcTaskRepository.java:101)
	at com.github.kagkarlsson.scheduler.SchedulerClient$StandardSchedulerClient.schedule(SchedulerClient.java:239)
	at com.github.kagkarlsson.scheduler.SchedulerClient$StandardSchedulerClient.schedule(SchedulerClient.java:246)
	at com.github.kagkarlsson.scheduler.Scheduler.schedule(Scheduler.java:173)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.Duration` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: com.github.kagkarlsson.scheduler.task.helper.PlainScheduleAndData["schedule"]->com.github.kagkarlsson.scheduler.task.schedule.FixedDelay["duration"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1276)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3765)
	at com.github.kagkarlsson.scheduler.serializer.JacksonSerializer.serialize(JacksonSerializer.java:69)
	... 100 more

```

then I change Serialize to DbSchedulerSerializer (to support Duration)
```
ublic class DbSchedulerSerializer implements Serializer {

    private final ObjectMapper objectMapper;

    public static ObjectMapper getDefaultObjectMapper() {

        return new ObjectMapper()
                .setNodeFactory(JsonNodeFactory.instance)
                .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                .enable(MapperFeature.DEFAULT_VIEW_INCLUSION)
                .enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES)
                .registerModule(new JavaTimeModule())
                .findAndRegisterModules()
                .setSerializationInclusion(JsonInclude.Include.NON_NULL);
    }

    public DbSchedulerSerializer() {
        this(getDefaultObjectMapper());
    }

    public DbSchedulerSerializer(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    public DbSchedulerSerializer(Consumer<ObjectMapper> objectMapperCustomizer) {
        ObjectMapper defaultObjectMapper = getDefaultObjectMapper();
        objectMapperCustomizer.accept(defaultObjectMapper);
        this.objectMapper = defaultObjectMapper;
    }

    @Override
    public byte[] serialize(Object object) {
        try {
            byte[] result =  objectMapper.writeValueAsString(object).getBytes(StandardCharsets.UTF_8);
            System.out.println("&&&&&&&&&&&&&&&");
            System.out.println(result);
            return result;
        } catch (JsonProcessingException e) {
            throw new SerializationException("Failed to serialize object.", e);
        }
    }

    @Override
    public <T> T deserialize(Class<T> clazz, byte[] serializedData) {
        try {
            System.out.println("-----------------------");
            System.out.println(serializedData);
            System.out.println(clazz);
            return objectMapper.readValue(serializedData, clazz);
        } catch (IOException e) {
            throw new SerializationException("Failed to deserialize object.", e);
        }
    }
}

```

then change scheduler
```

        final Scheduler scheduler = Scheduler
                .create(dataSource, task)
                .serializer(new DbSchedulerSerializer())
                .pollingInterval(Duration.ofSeconds(1))
                .registerShutdownHook()
                .build();

```

but it throw another exception 
```
2022-10-18 02:58:33.474 [] [db-scheduler-pool-5-thread-2] ERROR c.g.k.s.ExecutePicked - [failure,125] - Failed while completing execution Execution: task=dynamic-recurring-task, id=id2, executionTime=2022-10-18T02:58:32.453622Z, picked=true, pickedBy=xxxxx, lastHeartbeat=2022-10-18T02:58:33.454411Z, version=2. Execution will likely remain scheduled and locked/picked. The execution should be detected as dead after a while, and handled according to the tasks DeadExecutionHandler.
com.github.kagkarlsson.scheduler.exceptions.SerializationException: Failed to deserialize object.
	at com.xxxxx.xxxx.core.configuration.DbSchedulerSerializer.deserialize(DbSchedulerSerializer.java:68)
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository$ExecutionResultSetConsumer.lambda$map$0(JdbcTaskRepository.java:485)
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository$1.firstTime(JdbcTaskRepository.java:502)
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository$1.get(JdbcTaskRepository.java:498)
	at com.github.kagkarlsson.scheduler.task.TaskInstance.getData(TaskInstance.java:54)
	at com.github.kagkarlsson.scheduler.task.FailureHandler$OnFailureRescheduleUsingTaskDataSchedule.onFailure(FailureHandler.java:119)
	at com.github.kagkarlsson.scheduler.ExecutePicked.failure(ExecutePicked.java:120)
	at com.github.kagkarlsson.scheduler.ExecutePicked.executePickedExecution(ExecutePicked.java:92)
	at com.github.kagkarlsson.scheduler.ExecutePicked.run(ExecutePicked.java:68)
	at com.github.kagkarlsson.scheduler.FetchCandidates.lambda$run$1(FetchCandidates.java:89)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.github.kagkarlsson.scheduler.FetchCandidates.lambda$run$2(FetchCandidates.java:87)
	at com.github.kagkarlsson.scheduler.Executor.lambda$addToQueue$0(Executor.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.github.kagkarlsson.scheduler.task.helper.PlainScheduleAndData` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"schedule":{"deterministic":false,"disabled":false}}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1764)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1209)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
	at com.xxxxxxx.xxx.core.configuration.DbSchedulerSerializer.deserialize(DbSchedulerSerializer.java:66)
	... 15 common frames omitted
```

**Comment by kagkarlsson** [comment]
You should be able to pass the `ObjectMapper` to the `JacksonSerializer` I think. The default `ObjectMapper` is configured like this:

```
    public static ObjectMapper getDefaultObjectMapper() {
        SimpleModule module = new SimpleModule();
        module.addSerializer(Instant.class, new InstantSerializer());
        module.addDeserializer(Instant.class, new InstantDeserializer());

        return new ObjectMapper()
            .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
            .setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)
            .registerModule(module);
    }
```

Consider using `.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)`, that might fix it no?

**Comment by mumubin** [comment]
still error
```
    @SneakyThrows
    @Test
    void dbSchedulerDeleteRecordingJob() {

        final RecurringTaskWithPersistentSchedule<PlainScheduleAndData> task =
                Tasks.recurringWithPersistentSchedule("dynamic-recurring-task", PlainScheduleAndData.class)
                        .execute((taskInstance, executionContext) -> {
                            System.out.println("Instance: '" + taskInstance.getId() + "' ran using persistent schedule: " + taskInstance.getData()
                                    .getSchedule());
                        });


        ObjectMapper OM = new ObjectMapper()
                .setNodeFactory(JsonNodeFactory.instance)
                .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                .setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)
                .enable(MapperFeature.DEFAULT_VIEW_INCLUSION)
                .enable(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES)
                .registerModule(new JavaTimeModule())
                .findAndRegisterModules()
                .setSerializationInclusion(JsonInclude.Include.NON_NULL);
        final Scheduler scheduler = Scheduler
                .create(dataSource, task)
                .serializer(new JacksonSerializer(OM))
                .pollingInterval(Duration.ofSeconds(1))
                .registerShutdownHook()
                .build();


        scheduler.start();

        scheduler.schedule(task.schedulableInstance("id1", new PlainScheduleAndData(Schedules.fixedDelay(Duration.ofMinutes(1)))));
        scheduler.schedule(task.schedulableInstance("id2", new PlainScheduleAndData(Schedules.fixedDelay(Duration.ofSeconds(6)))));
    }
```

exception
```
2022-10-19 07:55:00.909 [] [db-scheduler-pool-8-thread-2] ERROR c.g.k.s.ExecutePicked - [failure,125] - Failed while completing execution Execution: task=dynamic-recurring-task, id=id2, executionTime=2022-10-19T07:54:59.906893Z, picked=true, pickedBy=xxxx, lastHeartbeat=2022-10-19T07:55:00.883832Z, version=2. Execution will likely remain scheduled and locked/picked. The execution should be detected as dead after a while, and handled according to the tasks DeadExecutionHandler.
com.github.kagkarlsson.scheduler.exceptions.SerializationException: Failed to deserialize object.
	at com.github.kagkarlsson.scheduler.serializer.JacksonSerializer.deserialize(JacksonSerializer.java:80)
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository$ExecutionResultSetConsumer.lambda$map$0(JdbcTaskRepository.java:485)
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository$1.firstTime(JdbcTaskRepository.java:502)
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository$1.get(JdbcTaskRepository.java:498)
	at com.github.kagkarlsson.scheduler.task.TaskInstance.getData(TaskInstance.java:54)
	at com.github.kagkarlsson.scheduler.task.FailureHandler$OnFailureRescheduleUsingTaskDataSchedule.onFailure(FailureHandler.java:119)
	at com.github.kagkarlsson.scheduler.ExecutePicked.failure(ExecutePicked.java:120)
	at com.github.kagkarlsson.scheduler.ExecutePicked.executePickedExecution(ExecutePicked.java:92)
	at com.github.kagkarlsson.scheduler.ExecutePicked.run(ExecutePicked.java:68)
	at com.github.kagkarlsson.scheduler.FetchCandidates.lambda$run$1(FetchCandidates.java:89)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.github.kagkarlsson.scheduler.FetchCandidates.lambda$run$2(FetchCandidates.java:87)
	at com.github.kagkarlsson.scheduler.Executor.lambda$addToQueue$0(Executor.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.github.kagkarlsson.scheduler.task.helper.PlainScheduleAndData` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (byte[])"{"schedule":{"duration":6.000000000,"deterministic":false,"disabled":false}}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1764)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1209)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
	at com.github.kagkarlsson.scheduler.serializer.JacksonSerializer.deserialize(JacksonSerializer.java:78)
	... 15 common frames omitted
```

**Comment by Sprytin** [comment]
Check https://github.com/kagkarlsson/db-scheduler/pull/338. It Fixed your problem with jackson json and java serializer

**Comment by kagkarlsson** [comment]
Closing, reopen if still an issue
