### ISSUE TITLE
MSSQL wrong data type for task_data column

### ISSUE THREAD

**Issue by quaso** [kagkarlsson/db-scheduler#354]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Serialization/deserialization of task data works in MSSQL

## Current Behavior

Serialization/deserialization of task data does not work in MSSQL, because of wrong data type. According to documentation nvarbinary should be used to store binary data, however nvarchar is used.
https://learn.microsoft.com/en-us/sql/t-sql/data-types/binary-and-varbinary-transact-sql?redirectedfrom=MSDN&view=sql-server-ver16. After changing the column data type, serialization/deserialization works as expected.

--------
# For bug reports
**YOU MAY DELETE THE `For bug reports` SECTION IF A NEW FEATURE REQUEST.**

## Steps to Reproduce the bug
1. use MSSQL as a persistent storage
2. create task with any data
3. wait for task to be triggered

## Context
- DB-Scheduler Version : 11.6
- Java Version : 17,0,6
- Spring Boot (check for Yes) : [x]
- Database and Version : mcr.microsoft.com/mssql/server:2019-latest

**Comment by kagkarlsson** [comment]
Thank you for reporting. This schema was supplied by a MSSQL user I think. Feel free to supply a PR with corrections :)

**Comment by kagkarlsson** [comment]
Slightly surprised that it breaks serialization/deserialization and not reported until now

**Comment by rafaelhofmann** [comment]
We are running MSSQL 2019 and we do not have this problem, although we use a lot of tasks with task data in our system.
Our `task_data` column is defined as an `nvarchar(max)`.

**Comment by kagkarlsson** [comment]
Thank you for pitching in @rafaelhofmann . Are you both using standard serialization?

**Comment by quaso** [comment]
Yes I am.
This is the way how I create a task
```
 scheduler.schedule(
                    task.schedulableInstance("inst-${param}", PlainScheduleAndData(Schedules.cron(cron), param))
                )
```
And I receive deserialization error

**Comment by kagkarlsson** [comment]
Would you also post the exception @quaso ?

**Comment by kagkarlsson** [comment]
There is a MSSQL integration-test that I have had to disable because it was failing (and no time to fix). If we could get that running again, it might make testing feedback-loop a bit shorter.

https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/test/java/com/github/kagkarlsson/scheduler/compatibility/MssqlCompatibilityTest.java

**Comment by quaso** [comment]
```
com.github.kagkarlsson.scheduler.exceptions.SerializationException: Failed to deserialize object
	at com.github.kagkarlsson.scheduler.boot.autoconfigure.DbSchedulerAutoConfiguration$2.deserialize(DbSchedulerAutoConfiguration.java:234) ~[db-scheduler-spring-boot-starter-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository$ExecutionResultSetConsumer.lambda$map$0(JdbcTaskRepository.java:485) ~[db-scheduler-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository$1.firstTime(JdbcTaskRepository.java:502) ~[db-scheduler-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.jdbc.JdbcTaskRepository$1.get(JdbcTaskRepository.java:498) ~[db-scheduler-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.task.TaskInstance.getData(TaskInstance.java:54) ~[db-scheduler-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.task.FailureHandler$OnFailureRescheduleUsingTaskDataSchedule.onFailure(FailureHandler.java:119) ~[db-scheduler-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.ExecutePicked.failure(ExecutePicked.java:120) ~[db-scheduler-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.ExecutePicked.executePickedExecution(ExecutePicked.java:92) ~[db-scheduler-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.ExecutePicked.run(ExecutePicked.java:68) ~[db-scheduler-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.FetchCandidates.lambda$run$1(FetchCandidates.java:89) ~[db-scheduler-11.6.jar:na]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at com.github.kagkarlsson.scheduler.FetchCandidates.lambda$run$2(FetchCandidates.java:87) ~[db-scheduler-11.6.jar:na]
	at com.github.kagkarlsson.scheduler.Executor.lambda$addToQueue$0(Executor.java:52) ~[db-scheduler-11.6.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.io.StreamCorruptedException: invalid stream header: 3F3F3F3F
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:958) ~[na:na]
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:392) ~[na:na]
	at org.springframework.core.ConfigurableObjectInputStream.<init>(ConfigurableObjectInputStream.java:65) ~[spring-core-5.3.25.jar:5.3.25]
	at org.springframework.core.ConfigurableObjectInputStream.<init>(ConfigurableObjectInputStream.java:51) ~[spring-core-5.3.25.jar:5.3.25]
	at com.github.kagkarlsson.scheduler.boot.autoconfigure.DbSchedulerAutoConfiguration$2.deserialize(DbSchedulerAutoConfiguration.java:231) ~[db-scheduler-spring-boot-starter-11.6.jar:na]
	... 15 common frames omitted
```

**Comment by quaso** [comment]
https://github.com/quaso/db-scheduler-mssql

This is sample project which replicates the error

**Comment by rafaelhofmann** [comment]
We use the `JavaSerializer`.

**Comment by quaso** [comment]
It is not about serialization, but database column type. Varchar is not supposed to contain binary data.

**Comment by kagkarlsson** [comment]
Not sure what to do with this since it is working for some. Maybe add `setData(..)`/ `getData(...)` methods to [JdbcCustomization](https://github.com/kagkarlsson/db-scheduler/blob/master/db-scheduler/src/main/java/com/github/kagkarlsson/scheduler/jdbc/JdbcCustomization.java) to make it customizable..

**Comment by quaso** [comment]
I found the issue - it is the java driver. We use jtds one. When I changed that to ms one, everything works.

**Comment by quaso** [comment]
I completely reimplemented the fix, so it uses `MssqlJdbcCustomization`. If jTDS driver is in use, then other way of retrieving bytes from varchar column is used. I tested that in sample project provided earlier and it works. The change should not have any effect on other MSSQL drivers.
