### ISSUE TITLE
Disabling the scheduler

### ISSUE THREAD

**Issue by cash1981** [kagkarlsson/db-scheduler#86]
Hi!

I am using db-scheduler-boot-starter and in my tests I don't want the scheduler to run. I keep getting this output because I don't want to configure flyway to create the tables in h2 database which I am using in my tests.

Something like this is in the outputs:
```
28/01/2020 12:50:32.740 [main] INFO  c.g.kagkarlsson.scheduler.Scheduler - Starting scheduler.
28/01/2020 12:50:32.776 [db-scheduler-execute-due-pool-2-thread-1] ERROR c.g.k.scheduler.RunUntilShutdown - Unhandled exception. Will keep running.
com.github.kagkarlsson.jdbc.SQLRuntimeException: Error when preparing statement.
	at com.github.kagkarlsson.jdbc.JdbcRunner.lambda$execute$3(JdbcRunner.java:56)
	at com.github.kagkarlsson.jdbc.JdbcRunner.withConnection(JdbcRunner.java:97)
	at com.github.kagkarlsson.jdbc.JdbcRunner.execute(JdbcRunner.java:48)
	at com.github.kagkarlsson.jdbc.JdbcRunner.query(JdbcRunner.java:44)
	at com.github.kagkarlsson.scheduler.JdbcTaskRepository.getDue(JdbcTaskRepository.java:125)
	at com.github.kagkarlsson.scheduler.Scheduler.executeDue(Scheduler.java:181)
	at com.github.kagkarlsson.scheduler.RunUntilShutdown.run(RunUntilShutdown.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "scheduled_tasks" not found; SQL statement:
select * from scheduled_tasks where picked = ? and execution_time <= ? order by execution_time asc [42102-200]

```

It would be nice with a property in spring where I could easily disable the scheduler from initilazing.
For instance 
`kagkarlsson.db-scheduler.enabled = false`
which would not initialize the and start the scheduler so that I can keep my logs clean in the tests.

**Comment by kagkarlsson** [comment]
Sounds like a reasonable request :)

Not strong on Spring Boot myself, is that something you would consider contributing?

**Comment by cash1981** [comment]
Sure I can give it a shot. Don't know exactly when I will have time to do it though.

**Comment by kagkarlsson** [comment]
I have not had the time to check it, but the [doc](https://github.com/kagkarlsson/db-scheduler#configuration-options) implies that there is already such a property. Have you tried that? (Spring Boot support was contributed by @evenh and I don't know the finer details yet myself)

**Comment by evenh** [comment]
That's correct @kagkarlsson. By setting `db-scheduler.enabled=false` the autoconfiguration shouldn't kick in.


There is a test for it as well:

https://github.com/kagkarlsson/db-scheduler/blob/b4722c45fda4a38cc2743f88d5170f9d910fecd7/db-scheduler-boot-starter/src/test/java/com/github/kagkarlsson/scheduler/boot/autoconfigure/DbSchedulerAutoConfigurationTest.java#L86-L93

Could probably be extended to include these lines as well:
```
assertThat(ctx).doesNotHaveBean(DbSchedulerStarter.class);
assertThat(ctx).doesNotHaveBean(DbSchedulerCustomizer.class);
assertThat(ctx).doesNotHaveBean(DbSchedulerHealthIndicator.class);
```

**Comment by cash1981** [comment]
Excellent thanks 🙂

**Comment by kagkarlsson** [comment]
Hey btw, may I ask you @cash1981 , are you using db-scheduler at Nordea? I see you are a member of their Github org. Just trying to get a sense of where it is being used :)

**Comment by cash1981** [comment]
Yes. 🙂

**Comment by kagkarlsson** [comment]
Ok thanks, appreciate it! FYI it is also in use at Digipost and Vy.
